
name: Build and Deploy to EKS

on:
  push:
    branches:
      - master

env:

  AWS_REGION: eu-west-1                   # set this to your preferred AWS region, e.g. us-west-1
  CONTAINER_NAME: my_app
  REGISTRY: ghcr.io
  IMAGE_NAME: gladandres
  IMAGE: static-site

  DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: pet

    steps:
    - name: Checkout
      uses: actions/checkout@v3
# 
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
#     - name: Docker configuration
#       run: |-
#         echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$GITHUB_SHA

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

#     # Build the Docker image
#     - name: Build
#       run: |-
#         docker build \
#           --tag "$DOCKER_REPO_NAME/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
#           --build-arg GITHUB_SHA="$GITHUB_SHA" \
#           --build-arg GITHUB_REF="$GITHUB_REF" \
#           .
#     # Push the Docker image to GitHub
#     - name: Publish
#       run: |-
#         docker push "$DOCKER_REPO_NAME/$REPOSITORY/$IMAGE:$GITHUB_SHA"
    
#     - name: Build and push CONTAINER_NAME
#       uses: ianbelcher/eks-kubectl-action@1.5
#       with:
#         cluster_name: ${{ secrets.CLUSTER_NAME }}
#         args: set image --record deployment/pod-name pod-name=${{ steps.build.outputs.IMAGE_URL }}
    
    
#     # Set up kustomize
#     - name: Set up Kustomize
#       run: |-
#         curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
#         chmod u+x ./kustomize
#     # Deploy the Docker image to the GKE cluster
#     - name: Deploy
#       run: |-
#         # replacing the image name in the k8s template
#         ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA
#         ./kustomize build . | kubectl apply -f -
#         kubectl rollout status deployment/$DEPLOYMENT_NAME
#         kubectl get services -o wide
