
name: Build and Deploy to EKS

on:
  push:
    branches:
      - master

env:

  AWS_REGION: eu-west-1                   # set this to your preferred AWS region, e.g. us-west-1
  CONTAINER_NAME: my_app
  REGISTRY: ghcr.io
  IMAGE_NAME: gladandres/test
  # IMAGE: static-site
  CLUSTER_NAME: terragunt-kluster
  # DEPLOYMENT_NAME: gke-test # TODO: update to deployment name
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: pet

    steps:
    - name: Checkout
      uses: actions/checkout@v3
# 
#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ env.AWS_REGION }}

    - name: Log in to the Container registry
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.MY_SECRET_2021 }}
        
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        #tags: type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}


    
    # - name: Build and push CONTAINER_NAME
    #   uses: ianbelcher/eks-kubectl-action@1.5
    #   with:
    #     cluster_name: ${{ secrets.CLUSTER_NAME }}
    #     args: set image --record deployment/pod-name pod-name=${{ steps.build.outputs.IMAGE_URL }}
